In [1]:
import pandas as pd
import csv

import warnings
warnings.filterwarnings('ignore')

In [2]:
FB_df = pd.read_csv('./Supporter Columns_FR_FB leads.csv',encoding = 'cp950')
FB_df.head()

,系統編號,顯示名稱,姓氏,名字,性別,出生日期,電子郵件,電話,縣市,鄉鎮市區,街道地址,郵遞區號,群組,凍結,日期
0,NaN,曾鏡,NaN,NaN,NaN,NaN,zmr911123@gmail.com,886900021458,NaN,NaN,NaN,NaN,《FB Leads》201904阿根廷墮胎除罪,NaN,4/25/19
1,NaN,Jamie Chou,NaN,NaN,NaN,NaN,babylove0118@hotmail.com,886972863536,NaN,NaN,NaN,NaN,《FB Leads》201904阿根廷墮胎除罪,NaN,4/25/19
2,NaN,Yen Lee,NaN,NaN,NaN,NaN,pica911130@hotmail.com,886987769781,NaN,NaN,NaN,NaN,《FB Leads》201904阿根廷墮胎除罪,NaN,4/25/19
3,NaN,藍惠真,NaN,NaN,NaN,NaN,bluebeauty1231@gmail.com,886955886803,NaN,NaN,NaN,NaN,《FB Leads》201904阿根廷墮胎除罪,NaN,4/25/19
4,NaN,高肇遠,NaN,NaN,NaN,NaN,joy0715kao@gmail.com,886965235198,NaN,NaN,NaN,NaN,《FB Leads》201904阿根廷墮胎除罪,NaN,4/25/19

In [3]:
tag_list = []
tag_list.append(FB_df['群組'].unique())

In [4]:
F2F_df = pd.read_csv('./Supporter Columns_F2F.csv',encoding='cp950')
F2F_df.head()

,系統編號,顯示名稱,姓氏,名字,性別,出生日期,電子郵件,電話,縣市,鄉鎮市區,街道地址,郵遞區號,群組,凍結
0,NaN,NaN,侯,華堉,NaN,NaN,03105891@yahoo.com.tw,0933558507,NaN,NaN,NaN,NaN,《F2F》2019維塔莉娜明信片連署,NaN
1,NaN,NaN,蔡,沂璇,NaN,NaN,07122120@scu.edu.tw,0905517736,NaN,NaN,NaN,NaN,《F2F》2019維塔莉娜明信片連署,NaN
2,NaN,NaN,盧,奕瑋,NaN,NaN,1.nymph.ya@gmail.com,0908933588,NaN,NaN,NaN,NaN,《F2F》2019維塔莉娜明信片連署,NaN
3,NaN,NaN,譚,暢,NaN,NaN,1009841242@qq.com,0966415309,NaN,NaN,NaN,NaN,《F2F》2019維塔莉娜明信片連署,NaN
4,NaN,NaN,張,先生,NaN,NaN,105405015@nccu.edu.tw,0975975905,NaN,NaN,NaN,NaN,《F2F》2019維塔莉娜明信片連署,NaN

In [5]:
tag_list.append(F2F_df['群組'].unique())

In [6]:
Campaign_df = pd.read_csv('./Supporter Columns_Campaign.csv',encoding='cp950')
Campaign_df.head()

                  201807-201909 相關群組
0             【倡議】201807 挪威,泰貝赫_線上連署
1           【倡議】201807 美墨邊境, 難民_線上連署
2             【倡議】201808 中國,王全璋_線上連署
3  【倡議】201809 中國,新疆WhereAreThey_線上連署
4   【倡議】201809 緬甸,言論表達自由(路透社記者)_線上連署

In [7]:
tag_list.append(Campaign_df['201807-201909 相關群組'].unique())

In [8]:
tag_list

[array(['《FB Leads》201904阿根廷墮胎除罪', '《FB Leads》201906 Nasrin',
        '《FB Leads》201907 XUAR', '《FB Leads》201907 evergreen',
        '《FB Leads》201907 Sudan', '《FB Leads》201907 Venezuela',
        '《FB Leads》201909 HK extradition bill'], dtype=object),
 array(['《F2F》2019維塔莉娜明信片連署', '《F2F》2019瑪麗埃爾明信片連署',
        '《F2F》20190415-20190630阿根廷墮胎除罪',
        '《F2F》20190705-20190905蘇丹血腥鎮壓和平示威者'], dtype=object),
 array(['【倡議】201807 挪威,泰貝赫_線上連署', '【倡議】201807 美墨邊境, 難民_線上連署',
        '【倡議】201808 中國,王全璋_線上連署', '【倡議】201809 中國,新疆WhereAreThey_線上連署',
        '【倡議】201809 緬甸,言論表達自由(路透社記者)_線上連署', '【倡議】201809 台灣,LGBTI_線上連署',
        '【倡議】201810 泰國,中國難民_線上連署', '【倡議】201811 台灣,李明哲_線上連署',
        '【倡議】201811 香港,聲援雨傘運動_線上連署', '【倡議】18W4R 巴西HRD瑪莉埃爾_線上連署',
        '【倡議】18W4R 烏克蘭HRD 維塔莉娜_線上連署', '【倡議】18W4R 教師行動計畫',
        '【倡議】18W4R 派對/活動/官網', '【倡議】201901 中國,新疆WhereAreThey_線上連署',
        '【倡議】201901 中國,王全璋_線上連署', '【倡議】201902 台灣,李明哲_線上連署',
        '【倡議】201903 台灣,李明哲_FB', '【倡議】201903 伊朗,納斯林(Nasrin Sotoudeh)_線上連署',
        '【倡議】201904 中國,新疆WhereAreThey_FB', '【倡議】201904 阿根廷,聲援墮胎_線上連署',
        '【倡議】201904 台灣,邱和順,生日祝福行動', '【倡議】201905香港,釋放佔中九子_線上連署',
        '【倡議】201905香港,釋放佔中九子_Event', '【倡議】201905 中國,八酒六四陳兵_線上連署',
        '【倡議】201905 中國,八酒六四陳兵_FB', '【倡議】201905 伊朗,納斯林(Nasrin Sotoudeh)',
        '【倡議】201906 香港反引渡條例警察暴力_線上連署', '【倡議】201906 香港反引渡條例警察暴力_Event',
        '【倡議】201906 蘇丹停止攻擊示威者_線上連署', '【倡議】201906 蘇丹停止攻擊示威者_Event',
        '【倡議】201906 希臘,柴克_線上連署', '【倡議】201906 希臘,柴克(FB)',
        '【倡議】201906 希臘,柴克_Event', '【倡議】201907 委內瑞拉, 難民/移民_線上連署',
        '【倡議】201907 中國,王全璋_FB', '【倡議】201908 中國,新疆布再娜甫_FB',
        '【倡議】201908 中國,新疆布再娜甫_Event', '【倡議】201909 厄瓜多_保衛亞馬遜的女性_線上連署',
        '【倡議】201909 巴西_保護原住民及亞馬遜_線上連署', '【倡議】201909 巴西_保護原住民及亞馬遜_FB',
        '【倡議】201909 南韓,廢止軍中同性行為定罪_線上連署'], dtype=object)]

In [91]:
supporter_df = pd.read_csv('./20191015_Supporter_All.csv',encoding = 'cp950')
supporter_df.head()

,Home-電子郵件,標籤,系統編號,不要寄Email,不要打電話,不要寄送郵政信件,群組,Actions
0,info@amnesty.tw,NaN,1,NaN,NaN,NaN,NaN,0.0
1,NaN,NaN,2,NaN,NaN,NaN,2015寫信馬拉松ALL IN ONE,0.0
2,illusmoon@gmail.com,General,3,NaN,NaN,NaN,"【倡議】20150509 倡議聯絡人,【倡議】General群組",0.0
3,klavier1976+t@gmail.com,"MBMR,測試連署,General,2014LWM",4,NaN,NaN,NaN,"【倡議】2014 LWM 連署人,【倡議】20150509 倡議聯絡人,【倡議】布吉納法索避...",0.0
4,NaN,NaN,7,NaN,NaN,NaN,團體組織,0.0

In [130]:
for i in range(len(supporter_df['群組'])):
    if supporter_df['群組'].isnull()[i] == False:
        for tag in tag_list[2][0:6]:
            if tag.split(',')[0] in supporter_df['群組'][i].split(',') and tag.split(',')[1] in supporter_df['群組'][i].split(','):
                supporter_df['Actions'][i] -= 1

In [140]:
verify = 0
for i in range(len(supporter_df['群組'])):
    if supporter_df['群組'].isnull()[i] == False:
            if tag_list[2][3].split(',')[0] in supporter_df['群組'][i].split(',') and tag_list[2][3].split(',')[1] in supporter_df['群組'][i].split(','):
                verify += 1
print(verify)

999

In [131]:
supporter_df['Actions'].sum()

63465.0

In [134]:
supporter_df.to_csv('./20191015_Supporter_All.csv',index=False,encoding='cp950')